Repository cert-manager/testing, pull requests merged in 2018-11, with the labels that each got.

#105 Use bazelbuild image for all cert-manager presubmits
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/S

#107 Add always_run: true to cert-manager bazel job
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/XS

#108 Add cert-manager release-0.6 presubmits
  config/jobs/cert-manager/releases/cert-manager-release-0.6.yaml
Labels: size/L

#111 Revert "Revert "Bump kind images for latest version""
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  config/jobs/cert-manager/releases/cert-manager-release-0.6.yaml
Labels: size/L

#112 Collate cert-manager presubmits into a single -bazel job
  config/config.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/L

#113 Add squash_label configuration
  config/config.yaml
Labels: size/XS

#114 Remove run_if_changed from cert-manager presubmits
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/XS

#116 Add flightdeck periodics
  config/jobs/flightdeck/flightdeck-periodics.yaml
Labels: size/S

#121 Update kubernetes versions tested
  config/jobs/tarmak/tarmak-presubmits.yaml
Labels: size/M
