Repository cert-manager/testing, pull requests merged in 2018-08, with the labels that each got.

#17 Output test errors
  .bazelrc
Labels: size/XS

#20 Disable DCO plugin until we have proper images built
  config/plugins.yaml
Labels: size/XS

#23 Fix bazel build failure
  legacy/BUILD.bazel
  legacy/images/tarmak/BUILD.bazel
Labels: size/XS

#14 Build our own Prow component images
  WORKSPACE
  hack/print-workspace-status.sh
  prow/README.md
  prow/cluster/BUILD.bazel
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/splice_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
  prow/prow.bzl
Labels: size/L

#24 Switch cert-manager to use new testing repo bootstrap images
  config/jobs/cert-manager/cert-manager-optional.yaml
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: dco-signoff: no, size/S

#25 Enable DCO plugin for cert-manager
  config/plugins.yaml
Labels: dco-signoff: yes, size/XS

#27 Add consul presubmits to testing
  config/jobs/tarmak/tarmak-presubmits.yaml
  legacy/jobs/config.json
Labels: size/M

#31 Bump bazelbuild presubmit
  config/jobs/testing/testing-presubmits.yaml
Labels: size/XS

#32 Add dedicated images presubmit for testing repo
  config/jobs/testing/testing-presubmits.yaml
Labels: size/M

#33 Switch all jobs to use updated images
  config/jobs/cert-manager/cert-manager-canaries.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  config/jobs/navigator/navigator-presubmits.yaml
  config/jobs/tarmak/extras-presubmits.yaml
Labels: size/L
