Repository cert-manager/testing, pull requests merged in 2018-09, with the labels that each got.

#39 Use our own images for decorated jobs
  config/config.yaml
  prow/cluster/BUILD.bazel
Labels: size/S

#40 Set default org and repo to k/k so all our repo logs are uploaded correctly
  config/config.yaml
Labels: size/XS

#41 Bump bazelbuild presubmits & install extra plugins
  config/jobs/testing/testing-presubmits.yaml
  config/plugins.yaml
Labels: size/S

#26 Enable strict mode on checkconfig
  config/plugins.yaml
  config/verify.sh
Labels: dco-signoff: no, size/S

#46 Enable DCO for vault-unsealer and migrate to new job format
  config/jobs/tarmak/extras-presubmits.yaml
  config/jobs/vault-unsealer/vault-unsealer-presubmits.yaml
  config/plugins.yaml
Labels: size/M

#47 Fix image tags for gcloud-in-go:v20180831-6e6e29c
  config/jobs/navigator/navigator-presubmits.yaml
  config/jobs/tarmak/tarmak-presubmits.yaml
Labels: size/XS

#48 Migrate tarmak quick-verifys to decorate style
  config/jobs/tarmak/tarmak-postsubmits.yaml
  config/jobs/tarmak/tarmak-presubmits.yaml
  config/jobs/vault-unsealer/vault-unsealer-presubmits.yaml
  legacy/jobs/config.json
Labels: size/L

#49 Migrate tarmak quick verifys
  config/jobs/tarmak/tarmak-postsubmits.yaml
  config/jobs/tarmak/tarmak-presubmits.yaml
  config/jobs/vault-unsealer/vault-unsealer-presubmits.yaml
Labels: size/S

#55 Enable dco tarmak kube lego
  config/plugins.yaml
Labels: size/XS

#56 Add katacoda-lint docker image
  WORKSPACE
  config/jobs/katacoda-scenarios/katacoda-scenarios-presubmits.yaml
  config/plugins.yaml
  images/BUILD.bazel
  images/katacoda-lint/BUILD.bazel
  images/katacoda-lint/Dockerfile
Labels: size/M

#58 Add vault_server tests
  config/jobs/tarmak/tarmak-presubmits.yaml
Labels: size/M

#60 Add kind based cert-manager e2e image
  WORKSPACE
  config/jobs/cert-manager/cert-manager-canaries.yaml
  images/BUILD.bazel
  images/bazelbuild/BUILD.bazel
  images/cert-manager/e2e/BUILD.bazel
Labels: size/L

#61 Update kind presubmit job config
  config/jobs/cert-manager/cert-manager-canaries.yaml
Labels: size/S

#66 Switch cert-manager to use kind e2e jobs by default
  config/jobs/cert-manager/cert-manager-canaries.yaml
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/L

#67 Disable 1.10 test. Rename and cleanup cert-manager jobs.
  config/jobs/cert-manager/cert-manager-optional.yaml
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  legacy/jobs/config.json
Labels: size/L

#70 Remove tarmak config
  config/config.yaml
Labels: size/XS

#73 Add standalone docs verify job
  config/config.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/M

#74 Add dep to cert-manager e2e image
  WORKSPACE
  images/cert-manager/e2e/BUILD.bazel
Labels: size/XS

#75 Use single image for all cert-manager tests
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/S

#76 Fix dep symlink
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  images/cert-manager/e2e/BUILD.bazel
Labels: size/S

#77 Install mercurial in bazelbuild
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  images/bazelbuild/Dockerfile
Labels: size/M

#78 Split cert-manager presubmits up
  config/config.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/L

#80 Fix pulling repo in katacoda scenario
  config/config.yaml
  config/jobs/katacoda-scenarios/katacoda-scenarios-presubmits.yaml
Labels: size/XS

#82 Build kind from kubernetes-sigs/kind
  WORKSPACE
  images/cert-manager/e2e/BUILD.bazel
Labels: size/XS

#83 Bump cert-manager e2e images
  config/jobs/cert-manager/cert-manager-canaries.yaml
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: size/M

#84 Bump test-infra revision to include podutils fix
  WORKSPACE
  config/config.yaml
  config/plugins.yaml
  config/verify.sh
Labels: size/M

#86 Enable more plugins for katacoda-scenarios
  config/plugins.yaml
Labels: size/XS

#87 Adds nodejs dependency and reference docs run for tarmak
  config/jobs/tarmak/tarmak-postsubmits.yaml
  config/jobs/tarmak/tarmak-presubmits.yaml
  legacy/images/tarmak/sphinx-docs/Dockerfile
Labels: size/S

#88 Add some missing and updated commands for the katacoda-lint image
  images/katacoda-lint/Dockerfile
Labels: size/S

#90 Update katacoda-lint image with python3-yaml package
  images/katacoda-lint/Dockerfile
Labels: size/XS

#92 Update katacoda-lint image tag
  config/jobs/katacoda-scenarios/katacoda-scenarios-presubmits.yaml
Labels: size/XS
