Repository cert-manager/testing, pull requests merged in 2019-03, with the labels that each got.

#166 Remove uses of run_after_success from tarmak
  config/jobs/tarmak/tarmak-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#167 Bump test-infra version
  WORKSPACE
  prow/cluster/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, size/S

#163 Add bazel-0.22.0 image and remove unused images
  images/BUILD.bazel
  images/bazelbuild/BUILD.bazel
  images/cert-manager/e2e/BUILD.bazel
Labels: approved, dco-signoff: yes, size/M

#168 Update job URL template and bump podutils
  config/config.yaml
Labels: approved, dco-signoff: yes, size/S

#169 Remove duplicate cert-manager label
  config/labels.yaml
Labels: dco-signoff: yes

#170 Increase resource allocation on dep jobs
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: dco-signoff: no

#171 Fix artifacts links in Spyglass
  config/config.yaml
Labels: approved, lgtm

#172 Bump prow version
  WORKSPACE
Labels: dco-signoff: yes

#173 Enable presubmits for release-0.7 branch
  config/jobs/cert-manager/releases/cert-manager-release-0.7.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#174 Adds kube-oidc-proxy-ci
  WORKSPACE
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
  config/labels.yaml
  images/BUILD.bazel
  images/bazelbuild/BUILD.bazel
  images/golang-dind/BUILD.bazel
  images/golang-dind/Dockerfile
  images/golang-dind/OWNERS
  images/katacoda-lint/Dockerfile
Labels: dco-signoff: yes, do-not-merge/hold, size/L

#176 Fix config for kube-oidc-proxy
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#177 Add docker start wrapper to tests
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#178 Adds kube-oidc-proxy e2e test for Kubernetes v1.14
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#179 Enable labels sync for kube-oidc-proxy
  prow/cluster/labelsync_cronjob.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#180 Manage labels for tarmak
  config/labels.yaml
  prow/cluster/labelsync_cronjob.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
