Repository cert-manager/testing, pull requests merged in 2019-10, with the labels that each got.

#289 Require dco-signoff for tide and enable cert-manager codefreeze
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#290 Move all kube-oidc-proxy prow jobs over to GKE
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, area/kube-oidc-proxy, dco-signoff: yes, lgtm, size/XS

#291 Removes kube-oidc-proxy job need for ssh jobs and private pull
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, area/kube-oidc-proxy, dco-signoff: yes, lgtm, size/M

#293 Update cert-manager jobs for v0.12.0
  config/jobs/cert-manager/cert-manager-postsubmits.yaml
  config/jobs/cert-manager/releases/cert-manager-release-0.11.yaml
  config/plugins.yaml
Labels: approved, area/cert-manager, dco-signoff: yes, lgtm, size/L

#294 Add bazelbuild image with Bazel 1.0
  images/bazelbuild/build.yaml
Labels: approved, area/testing, dco-signoff: yes, lgtm

#295 Bump bazelbuild docker version
  images/bazelbuild/Dockerfile
  images/bazelbuild/build.yaml
Labels: approved, area/testing, dco-signoff: yes, lgtm, size/S

#296 add missing ;
  images/bazelbuild/Dockerfile
Labels: approved, area/testing, dco-signoff: yes, lgtm, size/XS

#297 Remove bazelbuild 1.0.0-rc3 image
  images/bazelbuild/build.yaml
Labels: approved, area/testing, dco-signoff: yes

#299 Use bazelbuild 1.0.0 images in cert-manager
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-postsubmits.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: approved, area/cert-manager, dco-signoff: yes, lgtm, size/M

#300 Update spyglass config for test coverage and testgrid
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#301 Enable experimental dind CLI
  config/config.yaml
Labels: approved, dco-signoff: yes

#302 bazelbuild: make DOCKER_CONFIG directory writable
  images/bazelbuild/runner
Labels: approved, area/testing, dco-signoff: yes, lgtm, size/XS

#304 Set FLAKE_ATTEMPTS to 2 in cert-manager e2e presubmits
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: approved, area/cert-manager, dco-signoff: yes, lgtm, size/S
