Repository cert-manager/testing, pull requests merged in 2019-04, with the labels that each got.

#186 Add path to checkconfig in presubmit
  config/jobs/testing/testing-presubmits.yaml
Labels: approved, dco-signoff: yes

#185 Fix prow config check failures
  config/config.yaml
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#181 Adds kube-oidc-proxy/demo CI job
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#183 Add image builder and pusher for CI images
  BUILD.bazel
  WORKSPACE
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  hack/BUILD.bazel
  images/BUILD.bazel
  images/alpine/BUILD.bazel
  images/alpine/build.yaml
  images/bazelbuild/BUILD.bazel
  images/bazelbuild/Dockerfile
  images/bazelbuild/build.yaml
  images/bazelbuild/coalesce.py
  images/bazelbuild/coalesce_test.py
  images/bazelbuild/runner
  images/builder/BUILD.bazel
  images/builder/README.md
  images/builder/ci-runner.sh
  images/builder/main.go
  images/cert-manager/OWNERS
  images/golang-dind/BUILD.bazel
  images/golang-dind/build.yaml
  images/katacoda-lint/BUILD.bazel
  images/katacoda-lint/build.yaml
  images/tarmak/ruby/Dockerfile
  images/tarmak/ruby/build.yaml
  images/tarmak/sphinx-docs/Dockerfile
  images/tarmak/sphinx-docs/build.yaml
  images/tarmak/sphinx-docs/requirements.txt
  legacy/BUILD.bazel
  legacy/images/gcloud-in-go/BUILD.bazel
  legacy/images/gcloud-in-go/Dockerfile
  legacy/images/minikube-in-go/BUILD.bazel
  legacy/images/tarmak/BUILD.bazel
  legacy/images/tarmak/ruby/BUILD.bazel
  legacy/images/tarmak/sphinx-docs/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#187 Modify bazelbuild README
  images/bazelbuild/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#188 Set CWD when running git commands
  images/builder/main.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#189 More jetstack/testing jobs
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/testing/testing-trusted.yaml
  images/builder/ci-runner.sh
  images/builder/main.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#191 Activate service account in ci-runner.sh
  hack/verify-boilerplate.py
  images/builder/ci-runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#190 Add 3.7 and 3.8 alpine variants
  images/alpine/Dockerfile
  images/alpine/build.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#192 Bump bazelbuild image used in CM and testing
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-postsubmits.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/testing/testing-trusted.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#193 Build bazel 0.21.0 image
  images/bazelbuild/build.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#194 Fix bazel build warnings
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, size/S

#195 Create README.md
  images/tarmak/ruby/README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#197 Remove Bazel files from legacy/
  BUILD.bazel
  legacy/BUILD.bazel
  legacy/README.md
  legacy/bootstrap/BUILD.bazel
  legacy/images/gcloud-in-go/BUILD.bazel
  legacy/images/minikube-in-go/BUILD.bazel
  legacy/jobs/BUILD.bazel
  legacy/scenarios/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, size/M

#198 Update Prow manifest bugs
  prow/cluster/BUILD.bazel
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/ghproxy_deployment.yaml
  prow/cluster/ghproxy_service.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#200 Install openssh-client in bazelbuild image
  images/bazelbuild/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#199 Add missing manifests to Prow deployment target
  prow/cluster/BUILD.bazel
  prow/cluster/pushgateway.yaml
  prow/prow.bzl
Labels: approved, dco-signoff: yes, lgtm, size/M

#201 Remove unusued defs directory
  BUILD.bazel
  def/BUILD.bazel
  def/bootstrap.bzl
  def/build-image.sh
  def/container.bzl
Labels: approved, dco-signoff: yes, lgtm, size/L

#202 Fixes kube-oidc-proxy-demo demo test
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#203 Bump bazelbuild to debian stretch
  images/bazelbuild/Dockerfile
Labels: approved, dco-signoff: no, size/XS

#204 Automate bumping ProwJob configs when new images are pushed
  BUILD.bazel
  WORKSPACE
  config/jobs/testing/testing-trusted.yaml
  images/builder/ci-runner.sh
  images/builder/main.go
  tools/image-bumper/BUILD.bazel
  tools/image-bumper/main.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#205 Cleanup old statement in bazelbuild image
  images/bazelbuild/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#207 Add DCO sign off to autobump commits
  images/builder/ci-runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#208 Update tarmak-ruby README.md
  images/tarmak/ruby/README.md
Labels: approved, dco-signoff: yes, lgtm

#213 Add --variant flag to image builder
  images/builder/main.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#216 Add experimental cert-manager periodic
  config/jobs/cert-manager/cert-manager-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#220 Rearrange job configs to all have OWNERS
  config/jobs/flightdeck/katacoda-scenarios-presubmits.yaml
  config/jobs/tarmak/vault-helper/vault-helper-presubmits.yaml
  config/jobs/tarmak/vault-unsealer/vault-unsealer-presubmits.yaml
  config/jobs/vault-plugin-auth-templated-aws/vault-plugin-auth-templated-aws-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#221 Remove unused alpine image
  config/jobs/testing/testing-trusted.yaml
  images/alpine/Dockerfile
  images/alpine/OWNERS
  images/alpine/build.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#223 Remove duplicate label
  config/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#224 Tarmak disable bootstap py
  config/jobs/tarmak/tarmak-presubmits.yaml
Labels: approved, area/tarmak, dco-signoff: yes, lgtm, size/L

#226 Add build definitions for terraform-google-gke-cluster
  config/jobs/testing/testing-trusted.yaml
  config/labels.yaml
  images/terraform-google-gke-cluster/OWNERS
  images/terraform-google-gke-cluster/build.yaml
Labels: approved, area/testing, dco-signoff: yes, lgtm, size/M

#225 Delete navigator-presubmits.yaml
  config/jobs/navigator/navigator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#227 Add terraform-google-gke-cluster presubmit
  config/jobs/terraform-google-gke-cluster/presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#228 Enable labelsync for terraform-google-gke-cluster
  prow/cluster/labelsync_cronjob.yaml
Labels: approved, area/prow, dco-signoff: yes, lgtm, size/XS

#229 Add Dockerfile for Terraform Google GKE cluster testing
  images/terraform-google-gke-cluster/Dockerfile
Labels: approved, area/terraform-gke, dco-signoff: yes, lgtm, size/S

#232 Version cert-manager postsubmit jobs
  config/jobs/cert-manager/cert-manager-postsubmits.yaml
Labels: approved, area/cert-manager, dco-signoff: yes, lgtm, size/M

#233 Bump Prow version
  config/config.yaml
  config/jobs/testing/testing-presubmits.yaml
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/cluster/tot_deployment.yaml
Labels: approved, area/prow, area/testing, dco-signoff: yes, lgtm, size/M

#235 Fix decorated ProwJob image names
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
