Repository cert-manager/testing, pull requests merged in 2019-12, with the labels that each got.

#318 Update milestoneapplier plugin config for cert-manager
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#317 Add hooks for release and build for preflight
  config/jobs/preflight/preflight-postsubmits.yaml
  config/jobs/preflight/preflight-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#319 Use image with docker for preflight postsubmits
  config/jobs/preflight/preflight-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#320 Preped runner to preflight ci args so it runs docker daemon
  config/jobs/preflight/preflight-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#321 Fix BASE_IMAGE golang-dind
  images/golang-dind/build.yaml
Labels: approved, area/kube-oidc-proxy, dco-signoff: yes, lgtm, size/XS

#322 Bump golang-dind image for preflight postsubmits
  config/jobs/preflight/preflight-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#305 Adds presubmit jobs for cert-manager-csi
  config/config.yaml
  config/jobs/cert-manager-csi/OWNERS
  config/jobs/cert-manager-csi/cert-manager-csi-presubmits.yaml
  config/labels.yaml
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#323 Update cert-manager release job configurations
  config/config.yaml
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-postsubmits.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  config/jobs/cert-manager/release-0.12/README.md
  config/jobs/cert-manager/release-0.12/cert-manager-release-0.12-periodics.yaml
  config/jobs/cert-manager/release-0.12/cert-manager-release-0.12-postsubmits.yaml
  config/jobs/cert-manager/release-0.12/cert-manager-release-0.12-presubmits.yaml
  config/jobs/cert-manager/release-next/cert-manager-release-next-periodics.yaml
Labels: approved, area/cert-manager, dco-signoff: yes, lgtm, size/L

#313 Change kube-oidc-proxy e2e tests to use new ginko format
  config/jobs/kube-oidc-proxy/kube-oidc-proxy-presubmits.yaml
Labels: approved, area/kube-oidc-proxy, dco-signoff: yes, lgtm, size/M
