Repository cert-manager/testing, pull requests merged in 2019-01, with the labels that each got.

#126 Bazel bump
  WORKSPACE
  images/bazelbuild/BUILD.bazel
Labels: size/S

#129 Place ssh_key_secrets under decoration_config
  config/jobs/katacoda-scenarios/katacoda-scenarios-presubmits.yaml
Labels: size/XS

#130 Add a bazel test //... presumbit job
  config/jobs/katacoda-scenarios/katacoda-scenarios-presubmits.yaml
Labels: size/M

#132 Fixes for katacoda-scenarios bazel test config
  config/jobs/katacoda-scenarios/katacoda-scenarios-presubmits.yaml
Labels: size/XS

#133 More Fixes for katacoda-scenarios bazel test config
  config/jobs/katacoda-scenarios/katacoda-scenarios-presubmits.yaml
Labels: size/XS

#136 Enabled cherry-pick-unapproved plugin for cert-manager
  config/plugins.yaml
Labels: size/XS

#138 Bump podutils default images
  config/config.yaml
Labels: size/XS

#135 Replace target_url with pr_status_base_url
  config/config.yaml
Labels: size/XS

#140 Update cert-manager jobs after v0.6 release
  config/jobs/cert-manager/cert-manager-periodics.yaml
  config/jobs/cert-manager/releases/cert-manager-release-0.5.yaml
  config/jobs/cert-manager/releases/cert-manager-release-0.6.yaml
Labels: size/L

#141 Bump test-infra
  WORKSPACE
Labels: size/XS

#139 Enable a consistent set of plugins across all repos
  config/config.yaml
  config/plugins.yaml
Labels: size/L

#72 Enable auto-labeler cronjob
  WORKSPACE
  config/labels.yaml
  config/plugins.yaml
  prow/cluster/BUILD.bazel
  prow/cluster/labelsync_cronjob.yaml
Labels: dco-signoff: yes, size/L

#143 Add dco-signoff label and update descriptions
  config/labels.yaml
Labels: dco-signoff: yes, size/S

#144 Delete cert-manager-periodics.yaml
  config/jobs/cert-manager/cert-manager-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#145 Add dco-signoff: no label
  config/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#146 Add OWNERS files
  OWNERS
  images/cert-manager/OWNERS
  images/cert-manager/e2e/BUILD.bazel
  images/katacoda-lint/OWNERS
Labels: dco-signoff: yes, size/S

#147 Add venafi-tpp credentials to cert-manager presubmits
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#150 cert-manager: rename provider labels and add new areas
  config/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#151 Fix labels.yaml
  config/labels.yaml
Labels: dco-signoff: yes

#149 Fix preset config
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#152 Add optional Kubernetes 1.13 cert-manager presubmit
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#154 Remove run_if_changed for 1.13 presubmit
  config/jobs/cert-manager/cert-manager-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
