Repository cert-manager/testing, pull requests merged in 2020-09, with the labels that each got.

#397 Prepare testing for the cert-manager v1.0 release
  config/config.yaml
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  config/jobs/cert-manager/release-next/cert-manager-release-next-periodics.yaml
  config/jobs/cert-manager/release-previous/cert-manager-release-previous-periodics.yaml
  config/jobs/cert-manager/release-previous/cert-manager-release-previous-presubmits.yaml
  config/plugins.yaml
Labels: approved, area/cert-manager, dco-signoff: yes, lgtm, size/L

#398 Default config changes for Jetstack
  config/config.yaml
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#399 Disabling DCO sign off for jetstack org itself
  config/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
