Repository cert-manager/testing, pull requests merged in 2020-01, with the labels that each got.

#325 Use 'squash' merge method for preflight
  config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#326 Add bazel 2.0 image
  images/bazelbuild/build.yaml
Labels: approved, area/testing, dco-signoff: yes, lgtm, size/S

#328 cert-manager: update job configs for v0.14 release cycle
  config/jobs/cert-manager/cert-manager-presubmits.yaml
  config/jobs/cert-manager/release-0.13/README.md
  config/jobs/cert-manager/release-0.13/cert-manager-release-0.13-periodics.yaml
  config/jobs/cert-manager/release-0.13/cert-manager-release-0.13-postsubmits.yaml
  config/jobs/cert-manager/release-0.13/cert-manager-release-0.13-presubmits.yaml
  config/jobs/cert-manager/release-next/cert-manager-release-next-periodics.yaml
  config/jobs/cert-manager/release-next/cert-manager-release-next-postsubmits.yaml
  config/plugins.yaml
Labels: approved, area/cert-manager, dco-signoff: yes, lgtm, size/M
