Repository cert-manager/testing, pull requests merged in 2023-08, with the labels that each got.

#896 Add kubernetes 1.28 as a test target on cert-manager master
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#897 Change master's primaryKubernetesVersion to 1.28
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#898 Update required status checks to 1.28
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#899 Disable automatic self-approval for PRs
  config/plugins.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#900 Only allow OWNERS to /lgtm
  config/plugins.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#902 Add trust-manager to the --only flag
  prow/cluster/labelsync_cronjob.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#903 Moving jetstack/testing to cert-manager/testing
  Makefile
  README.md
  config/autobump-config/testing-autobump-config.yaml
  config/config.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/testing/testing-periodics-trusted.yaml
  config/jobs/testing/testing-postsubmits-trusted.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/labels.yaml
  config/plugins.yaml
  images/README.md
  prow/Makefile
  prow/cluster/labelsync_cronjob.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#905 Test the pipeline by updating some quotes
  config/config.yaml
  config/jobs/cert-manager/config.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved
