Repository cert-manager/testing, pull requests merged in 2023-05, with the labels that each got.

#888 Add issuer-lib repo
  config/config.yaml
  config/plugins.yaml
  triage_party/triageparty_configmap.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#889 Bump cert-manager test config following 1.12 release
  config/config.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/plugins.yaml
  config/prowgen/prowspecs/specs.go
  config/testgrid/dashboards.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#879 Add prowgen to our CI
  .gitignore
  Makefile
  config/jobs/cert-manager/cert-manager/README.md
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/prowgen/main.go
  config/prowgen/pkg/generators.go
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#886 Add istio v1.17.2 as test target for istio-csr
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#885 Document steps necessary to setup worker cluster
  prow/Makefile
  prow/_hack/.gitignore
  prow/_hack/README.md
  prow/_hack/create_user.sh
  prow/_hack/crier-kubeconfig.yaml
  prow/_hack/kubeconfig.yaml
  prow/worker_cluster/role-binding-crier-get-pods.yaml
  prow/worker_cluster/role-binding-sinker.yaml
  prow/worker_cluster/role-binding-tide-gcp-admin-binding.yaml
  prow/worker_cluster/role-binding-tide.yaml
  prow/worker_cluster/role-get-test-pods.yaml
Labels: size/L, dco-signoff: yes, do-not-merge/hold, lgtm, approved

#891 Upgrade prowjob CRD
  prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
Labels: dco-signoff: yes, size/S, approved

#890 Use Recreate as deployment strategy for ghproxy
  prow/cluster/ghproxy.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved
