Repository cert-manager/testing, pull requests merged in 2023-10, with the labels that each got.

#906 Only protect branches master, main, and release-.*
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#911 Upgrade go dind images
  images/golang-dind/build.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#909 Apply upstream changes
  prow/cluster/crier_deployment.yaml
  prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#912 Use latest go 1.21.3 image in all prowjobs & base images
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/boilersuite/cert-manager-boilersuite.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  images/image-builder/build.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#914 Fix error in autobumper configuration
  config/autobump-config/testing-autobump-config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#913 Switch nodeport services to clusterIP
  prow/cluster/deck_service.yaml
  prow/cluster/hook_service.yaml
  prow/cluster/needs-rebase_service.yaml
  prow/cluster/pushgateway_deployment.yaml
  prow/cluster/tot_service.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#916 Tweak running test jobs for trust-manager
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#917 Bump golang version for testing istio-csr
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved
