Repository cert-manager/testing, pull requests merged in 2023-11, with the labels that each got.

#920 chore(approver-policy): replace golang image with jetstack:golang-dind
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#919 Add letsencrypt clusterissuer
  prow/cluster/letsencrypt-prod-clusterissuer.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#921 Limit dind mtu to 1460
  images/make-dind/Dockerfile
Labels: size/XS, dco-signoff: yes, lgtm, approved

#924 Bump make-dind
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/prowgen/pkg/globals.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#927 Upgrade make-dind to latest debian & docker version
  images/make-dind/Dockerfile
  images/make-dind/build.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#929 Re-add use of iptables-legacy
  images/make-dind/Dockerfile
Labels: size/XS, dco-signoff: yes, lgtm, approved

#928 Use latest make-dind images
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/prowgen/pkg/globals.go
  images/golang-dind/build.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#932 Update RBAC for worker cluster (add missing Role)
  prow/worker_cluster/cluster-role-tide.yaml
  prow/worker_cluster/role-sinker.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved
