Repository cert-manager/testing, pull requests merged in 2023-03, with the labels that each got.

#800 Bump golang-dind and add build env for golang 1.19.7
  images/golang-dind/build.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved, area/kube-oidc-proxy

#801 Apply new prow config
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved, area/cert-manager

#803 Bump cert-manager images with older golang-dind to newly built version
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, area/cert-manager

#805 Re-add GH required check for website
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#804 Add make-dind image
  config/jobs/testing/testing-trusted.yaml
  images/make-dind/Dockerfile
  images/make-dind/README.md
  images/make-dind/build.yaml
  images/make-dind/runner
Labels: size/L, dco-signoff: yes, lgtm, approved, area/testing

#806 Trigger make-dind build: remove comment
  images/make-dind/Dockerfile
Labels: size/XS, dco-signoff: yes, lgtm, approved

#808 Remove gcloud install, saving about 500MB from final image size
  images/make-dind/Dockerfile
Labels: dco-signoff: yes, size/M, lgtm, approved

#807 Add make-based golang image
  images/golang-dind/build.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved, area/kube-oidc-proxy

#811 Reduce size of go-dind image
  images/golang-dind/Dockerfile
Labels: size/XS, dco-signoff: yes, lgtm, approved, area/kube-oidc-proxy

#816 Rename cherrypick to cherrypicker in external_plugins
  config/plugins.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#817 Update utility_images
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved
