Repository cert-manager/testing, pull requests merged in 2023-04, with the labels that each got.

#819 Remove old image builds
  config/jobs/testing/testing-trusted.yaml
  images/katacoda-lint/Dockerfile
  images/katacoda-lint/OWNERS
  images/katacoda-lint/build.yaml
  images/tarmak/OWNERS
  images/tarmak/ruby/Dockerfile
  images/tarmak/ruby/README.md
  images/tarmak/ruby/build.yaml
  images/tarmak/sphinx-docs/Dockerfile
  images/tarmak/sphinx-docs/build.yaml
  images/tarmak/sphinx-docs/requirements.txt
  images/terraform-google-gke-cluster/Dockerfile
  images/terraform-google-gke-cluster/OWNERS
  images/terraform-google-gke-cluster/build.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved, area/flightdeck, area/testing, area/tarmak, area/terraform-gke

#820 Replace bazelbuild with make-dind (test)
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved, area/cert-manager

#821 Add missing jq tool to make-dind
  images/make-dind/Dockerfile
Labels: size/XS, dco-signoff: yes, lgtm, approved

#822 Use updated make-dind image that includes jq
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved, area/cert-manager

#823 Revert image change
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved, area/cert-manager

#812 Also install buildx in make-dind
  images/make-dind/Dockerfile
Labels: size/XS, dco-signoff: yes, approved

#825 export PWD variable
  images/make-dind/runner
Labels: dco-signoff: yes, approved

#826 Remaining improvements to make-dind
  images/make-dind/Dockerfile
  images/make-dind/runner
Labels: dco-signoff: yes, approved

#828 Upgrade base image for go-dind
  images/golang-dind/build.yaml
Labels: dco-signoff: yes, approved, area/kube-oidc-proxy

#809 Switch to make-dind for our tests
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved, area/testing, area/kube-oidc-proxy, area/cert-manager

#813 Cleanup presubmits
  config/config.yaml
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  config/jobs/cert-manager/config.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/csi-lib/cert-manager-csi-lib-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
  config/jobs/cert-manager/webhook-example/cert-manager-webhook-example-presubmits.yaml
  config/jobs/testing/testing-periodics.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/testing/testing-trusted.yaml
  hack/print-workspace-status.sh
Labels: size/L, dco-signoff: yes, lgtm, approved, area/flightdeck, area/testing, area/kube-oidc-proxy, area/cert-manager, area/okta-kubectl-auth, area/tarmak, area/terraform-gke

#830 BUGFIX: Replace make-dind with golang-dind where replaced incorrectly
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, area/cert-manager

#831 Add GOCACHE to cert-manager tests
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  config/jobs/cert-manager/config.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved, area/cert-manager

#834 Don't use underscore in volume name
  config/jobs/cert-manager/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved, area/cert-manager

#829 Use upstream Makefiles and scripts instead of bazel
  BUILD.bazel
  prow/BUILD.bazel
  prow/Makefile
  prow/OWNERS
  prow/README.md
  prow/bump/BUILD.bazel
  prow/cluster/BUILD.bazel
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/labelsync_cronjob.yaml
  prow/cluster/mem-limit-range_limitrange.yaml
  prow/mkpj.sh
  prow/pj-on-kind.sh
  prow/prow.bzl
  triage_party/BUILD.bazel
  triage_party/Makefile
Labels: size/L, dco-signoff: yes, lgtm, approved, area/prow

#835 Add GOMODCACHE
  config/jobs/cert-manager/config.yaml
Labels: size/XS, dco-signoff: yes, approved, area/cert-manager

#810 Use go-dind for building images
  config/jobs/testing/testing-trusted.yaml
  images/make-builder/README.md
  images/make-builder/ci-runner.sh
  images/make-builder/go.mod
  images/make-builder/go.sum
  images/make-builder/main.go
Labels: dco-signoff: yes, size/XL, approved, area/testing

#827 Add logic for local cache in make-dind
  images/make-dind/runner
Labels: dco-signoff: yes, size/M, approved

#838 Add postsubmits for image-builder
  config/jobs/testing/testing-trusted.yaml
Labels: dco-signoff: yes, approved, area/testing

#839 Use image-builder to build images
  config/jobs/testing/testing-trusted.yaml
Labels: dco-signoff: yes, approved, area/testing

#833 Start using new local cache
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  config/jobs/cert-manager/config.yaml
  images/golang-dind/build.yaml
Labels: size/L, dco-signoff: yes, approved, area/kube-oidc-proxy, area/cert-manager

#840 Correct typo from #833
  config/jobs/cert-manager/config.yaml
Labels: dco-signoff: yes, approved, area/cert-manager

#841 Improve runner script for cache and tune environment variables
  config/jobs/cert-manager/config.yaml
  images/make-dind/runner
Labels: dco-signoff: yes, size/M, approved, area/cert-manager

#842 Upgrade make-dind
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  images/golang-dind/build.yaml
Labels: dco-signoff: yes, approved, area/kube-oidc-proxy, area/cert-manager

#843 Copy directory contents instead of directory itself
  images/make-dind/runner
Labels: dco-signoff: yes, approved

#844 Upgrade make-dind
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  images/golang-dind/build.yaml
Labels: dco-signoff: yes, approved, area/kube-oidc-proxy, area/cert-manager

#845 fix typo
  images/golang-dind/build.yaml
Labels: dco-signoff: yes, approved, area/kube-oidc-proxy

#846 Use non-tmpfs volume to store caches
  config/jobs/cert-manager/config.yaml
Labels: size/XS, dco-signoff: yes, approved, area/cert-manager

#847 Reduce requested memory usage of e2e jobs
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: size/L, dco-signoff: yes, approved, area/cert-manager

#832 Remove unused image bazel-tools
  config/jobs/testing/testing-trusted.yaml
  images/bazel-tools/Dockerfile
  images/bazel-tools/build.yaml
  images/bazel-tools/semversort.sh
Labels: size/L, dco-signoff: yes, lgtm, approved, area/testing

#848 Remove all remaining bazel and OWNERS files
  .bazelrc
  .gitignore
  .kazelcfg.json
  BUILD.bazel
  Makefile
  OWNERS
  WORKSPACE
  config/BUILD.bazel
  config/config.yaml
  config/jobs/cert-manager/OWNERS
  config/jobs/cert-manager/approver-policy/OWNERS
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/csi-driver-spiffe/OWNERS
  config/jobs/cert-manager/csi-driver/OWNERS
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/csi-lib/OWNERS
  config/jobs/cert-manager/csi-lib/cert-manager-csi-lib-presubmits.yaml
  config/jobs/cert-manager/istio-csr/OWNERS
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/OWNERS
  config/jobs/testing/OWNERS
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/testing/testing-trusted.yaml
  hack/BUILD.bazel
  hack/boilerplate/BUILD.bazel
  hack/print-workspace-status.sh
  hack/verify-boilerplate.py
  hack/verify-kazel.sh
  images/bazelbuild/BUILD.bazel
  images/bazelbuild/OWNERS
  images/builder/BUILD.bazel
  images/builder/OWNERS
  images/golang-dind/OWNERS
  images/nix-dind/OWNERS
  prow/mkpj.sh
  tools/image-bumper/BUILD.bazel
  tools/image-bumper/OWNERS
Labels: dco-signoff: yes, size/XL, lgtm, approved, area/testing, area/kube-oidc-proxy, area/cert-manager

#849 Update README, add local tests and rename builder script
  Makefile
  README.md
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/testing/testing-trusted.yaml
  images/image-builder-script/README.md
  images/image-builder-script/builder.sh
Labels: size/L, dco-signoff: yes, do-not-merge/hold

#855 Fix entrypoint for checkconfig image
  config/jobs/testing/testing-presubmits.yaml
Labels: size/XS, dco-signoff: yes

#850 golang builder script: remove ioutil
  images/image-builder-script/main.go
Labels: size/XS, dco-signoff: yes

#856 Futher improve jetstack/testing presubmits (part1)
  config/jobs/testing/testing-presubmits.yaml
Labels: dco-signoff: yes, size/S

#857 verify-boilerplate: print message on success
  Makefile
Labels: dco-signoff: yes

#851 Generic autobumper
  config/autobump-config/testing-autobump-config.yaml
  config/jobs/testing/presets.yaml
  config/jobs/testing/testing-periodics.yaml
  config/jobs/testing/testing-trusted.yaml
Labels: size/L, dco-signoff: yes

#858 Generic autobumper: correct wrong config path
  config/jobs/testing/testing-periodics.yaml
Labels: dco-signoff: yes

#861 Revert "circumvent DCO check for generic auto-bumper"
  config/autobump-config/testing-autobump-config.yaml
Labels: size/XS, dco-signoff: yes

#862 Use latest commenter images and use correct flags
  config/jobs/testing/testing-periodics.yaml
Labels: dco-signoff: yes, size/S

#865 Added a correct OWNERS file
  OWNERS
Labels: dco-signoff: yes, size/S, lgtm, approved

#867 ghproxy: don't use legacy cache structure; fixes a warning on startup
  prow/cluster/ghproxy.yaml
Labels: size/XS, dco-signoff: yes, lgtm

#870 Double requested CPU for our e2e tests based on observed usage
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#871 Remove prow-build and prow-pipeline
  prow/cluster/build_deployment.yaml
  prow/cluster/build_rbac.yaml
  prow/cluster/pipeline_deployment.yaml
  prow/cluster/pipeline_rbac.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#854 Don't set a concurrency limit for make
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#873 Rename trusted cluster files and move commenter periodics to the trusted cluster
  config/jobs/testing/testing-periodics-trusted.yaml
  config/jobs/testing/testing-postsubmits-trusted.yaml
  config/jobs/testing/testing-presets-trusted.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#876 Move cronjobs to prowjobs
  config/jobs/testing/testing-periodics-trusted.yaml
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/labelsync_cronjob.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#874 Add DCO exception for jetstack-bot
  config/plugins.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#878 Revert "move label_sync and branchprotector from cronjob to prowjob"
  config/jobs/testing/testing-periodics-trusted.yaml
  prow/cluster/branchprotector_cronjob.yaml
  prow/cluster/labelsync_cronjob.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#881 Sync jobs with changes made in cert-manager/release
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.10/cert-manager-release-1.10.yaml
  config/jobs/cert-manager/cert-manager/release-1.11/cert-manager-release-1.11.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#880 Copy prowgen from cert-manager/release
  config/prowgen/go.mod
  config/prowgen/go.sum
  config/prowgen/main.go
  config/prowgen/pkg/configurers.go
  config/prowgen/pkg/configurers_test.go
  config/prowgen/pkg/context.go
  config/prowgen/pkg/generators.go
  config/prowgen/pkg/globals.go
  config/prowgen/pkg/types.go
  config/prowgen/pkg/util.go
  config/prowgen/pkg/util_test.go
  config/prowgen/prowspecs/specs.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#882 Setup testing repo presubmits so prowgen is tested & go is available for the verify target
  Makefile
  config/jobs/testing/testing-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#884 Add boilersuite presubmits
  config/config.yaml
  config/jobs/cert-manager/boilersuite/cert-manager-boilersuite.yaml
  prow/cluster/labelsync_cronjob.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved
