Repository cert-manager/testing, pull requests merged in 2024-05, with the labels that each got.

#1022 Switch from nginx to gke ingress and add annotation to use static ip
  prow/cert-manager_install.sh
  prow/cluster/deck_service.yaml
  prow/cluster/hook_service.yaml
  prow/cluster/tls-ing_ingress.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#1027 Fix k8s test versions for all supported cert-manager releases
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/prowgen/prowspecs/specs.go
Labels: dco-signoff: yes, size/XL, lgtm, approved

#1028 Add test setup for cert-manager release-1.15 branch
  config/config.yaml
  config/jobs/cert-manager/cert-manager/release-1.15/cert-manager-release-1.15.yaml
  config/plugins.yaml
  config/prowgen/prowspecs/specs.go
  config/testgrid/dashboards.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved
