Repository cert-manager/testing, pull requests merged in 2024-03, with the labels that each got.

#970 Bump make-dind for a new version
  README.md
  images/make-dind/bumper
Labels: dco-signoff: yes, size/S, lgtm, approved

#971 Bump to latest make-dind image everywhere
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/jobs/cert-manager/cert-manager/release-1.14/cert-manager-release-1.14.yaml
  config/jobs/cert-manager/cmctl/cert-manager-cmctl.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/helm-tool/cert-manager-helm-tool.yaml
  config/jobs/cert-manager/issuer-lib/cert-manager-issuer-lib-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/prowgen/pkg/globals.go
  images/golang-dind/build.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#973 Bump golang images for various components
  config/jobs/cert-manager/boilersuite/cert-manager-boilersuite.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
  config/jobs/testing/testing-postsubmits-trusted.yaml
  config/jobs/testing/testing-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#975 fix image typo
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved
