Repository cert-manager/testing, pull requests merged in 2024-01, with the labels that each got.

#937 fix incorrect use of annotations instead of labels
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#936 Upgrade Go dind global variable
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/prowgen/pkg/globals.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#939 Fix bug that causes caching to fail
  images/make-dind/runner
Labels: dco-signoff: yes, lgtm, approved

#938 Trying to speedup cache copying by using rsync
  images/make-dind/Dockerfile
  images/make-dind/runner
Labels: dco-signoff: yes, size/M, lgtm, approved

#940 Bump make-dind image: use rsync for cache
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/prowgen/pkg/globals.go
  images/golang-dind/build.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#941 Bump make-dind image: use rsync for cache
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/prowgen/pkg/globals.go
  images/golang-dind/build.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#944 Cleanup approver-policy prowjob yaml
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#943 istio-csr: Use new test target names (part of migration to makefile-modules)
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#945 Update cache logic so local and shared caches are merged
  images/make-dind/runner
Labels: dco-signoff: yes, size/S, lgtm, approved

#949 Cache: Speedup file transfer by disabling compression and using --inplace
  images/make-dind/runner
Labels: size/XS, dco-signoff: yes, lgtm, approved

#951 Bump make-dind version: cache - don't use compression
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/prowgen/pkg/globals.go
Labels: dco-signoff: yes, lgtm, approved

#954 Update csi-driver tests (part of makefile-module refactor)
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#953 Update csi-driver-spiffe tests (part of makefile-module refactor)
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#956 Add the helm-tool repo
  config/jobs/cert-manager/helm-tool/cert-manager-helm-tool.yaml
  config/plugins.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#957 Add Kubernetes 1.29 to the prow jobs for cert-manager master
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#958 Add tests for the cmctl repo
  config/jobs/cert-manager/cmctl/cert-manager-cmctl.yaml
  config/plugins.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#960 Add jobs / config for release-1.14
  config/config.yaml
  config/jobs/cert-manager/cert-manager/release-1.14/cert-manager-release-1.14.yaml
  config/plugins.yaml
  config/prowgen/prowspecs/specs.go
  config/testgrid/dashboards.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#961 Replace the trivy tests for the ctl image
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.14/cert-manager-release-1.14.yaml
  config/prowgen/prowspecs/specs.go
Labels: dco-signoff: yes, size/M, lgtm, approved
