Repository cert-manager/testing, pull requests merged in 2024-10, with the labels that each got.

#1062 Mitigate the impact of Trivy DB download rate limiting on GHCR by using a Trivy DB mirror
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.14/cert-manager-release-1.14.yaml
  config/jobs/cert-manager/cert-manager/release-1.15/cert-manager-release-1.15.yaml
  config/jobs/cert-manager/cert-manager/release-1.16/cert-manager-release-1.16.yaml
  config/jobs/cert-manager/config.yaml
  config/prowgen/pkg/configurers.go
  config/prowgen/pkg/generators.go
Labels: dco-signoff: yes, size/M, lgtm, approved

#1063 Omit the trivy DB schema version for backwards compatibility with trivy < 0.50.0
  config/jobs/cert-manager/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1065 Don't test master against k8s 1.27
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1066 Add Istio 1.24 test
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved, ok-to-test

#1067 istio-csr Test Cleanup / Addition
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-periodics.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/testgrid/dashboards.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#1068 Add dashboard group for istio-csr, fix comment
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-periodics.yaml
  config/testgrid/dashboards.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved
