Repository cert-manager/testing, pull requests merged in 2024-04, with the labels that each got.

#982 Use correct url for new infra image repository
  images/builder/README.md
  images/builder/ci-runner.sh
  images/builder/main.go
  images/image-builder-script/README.md
  images/image-builder-script/builder.sh
  images/image-builder-script/main.go
  images/kind/build.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#983 Replace images with images in new GCP project & remove unused images
  config/autobump-config/testing-autobump-config.yaml
  config/jobs/cert-manager/approver-policy/cert-manager-approver-policy-presubmits.yaml
  config/jobs/cert-manager/boilersuite/cert-manager-boilersuite.yaml
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/jobs/cert-manager/cert-manager/release-1.14/cert-manager-release-1.14.yaml
  config/jobs/cert-manager/cmctl/cert-manager-cmctl.yaml
  config/jobs/cert-manager/csi-driver-spiffe/cert-manager-csi-driver-spiffe-presubmits.yaml
  config/jobs/cert-manager/csi-driver/cert-manager-csi-driver-presubmits.yaml
  config/jobs/cert-manager/csi-lib/cert-manager-csi-lib-presubmits.yaml
  config/jobs/cert-manager/helm-tool/cert-manager-helm-tool.yaml
  config/jobs/cert-manager/issuer-lib/cert-manager-issuer-lib-presubmits.yaml
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
  config/jobs/testing/testing-postsubmits-trusted.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/prowgen/pkg/globals.go
  images/README.md
  images/bazelbuild/Dockerfile
  images/bazelbuild/README.md
  images/bazelbuild/build.yaml
  images/bazelbuild/coalesce.py
  images/bazelbuild/coalesce_test.py
  images/bazelbuild/create_bazel_cache_rcs.sh
  images/bazelbuild/runner
  images/builder/README.md
  images/builder/ci-runner.sh
  images/builder/main.go
  images/golang-dind/build.yaml
  images/golang-nodejs/Dockerfile
  images/golang-nodejs/build.yaml
  images/image-builder/build.yaml
  images/kind/build.sh
  images/nix-dind/build.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#985 Don't fix the go patch version
  config/jobs/cert-manager/boilersuite/cert-manager-boilersuite.yaml
  config/jobs/cert-manager/release/cert-manager-release-presubmits.yaml
  config/jobs/cert-manager/trust-manager/trust-manager-presubmits.yaml
  config/jobs/testing/testing-postsubmits-trusted.yaml
  config/jobs/testing/testing-presubmits.yaml
  images/image-builder/build.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#984 Use periodic prowjobs for label_sync and branchprotector
  config/jobs/testing/testing-periodics-trusted.yaml
  prow/cluster/_old/branchprotector_cronjob.yaml
  prow/cluster/_old/labelsync_cronjob.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#988 Fix failing cherrypicker deployment
  config/jobs/testing/testing-presets-trusted.yaml
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/needs-rebase_deployment.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#989 Add gencred image
  config/autobump-config/testing-autobump-config.yaml
  config/jobs/testing/testing-postsubmits-trusted.yaml
  images/gencred/Dockerfile
  images/gencred/README.md
  images/gencred/build.yaml
  images/gencred/go.mod
  images/gencred/go.sum
  images/gencred/main.go
  images/gencred/main_test.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#990 Fix copy-paste error: name was not updated to gencred
  images/gencred/build.yaml
Labels: dco-signoff: yes, lgtm, approved

#991 Use the new gencred image to automatically create the worker clusters' kubeconfigs
  config/gencred-config/gencred-config.yaml
  config/plugins.yaml
  prow/Makefile
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/gencred_deployment.yaml
  prow/cluster/gencred_rbac.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#993 Optimise make-dind image
  config/config.yaml
  images/make-dind/Dockerfile
  images/make-dind/build.yaml
  images/make-dind/runner
Labels: dco-signoff: yes, size/M, lgtm, approved

#994 Stop using python to verify license boilerplate
  Makefile
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.bzl.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/verify-boilerplate.py
Labels: size/L, dco-signoff: yes, lgtm, approved

#996 Upgrade global CommonTestImage
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/jobs/cert-manager/cert-manager/release-1.14/cert-manager-release-1.14.yaml
  config/prowgen/pkg/globals.go
Labels: dco-signoff: yes, lgtm, approved

#997 Update runner output & fix ulimit error
  images/make-dind/runner
Labels: dco-signoff: yes, lgtm, approved

#999 Fix runtime calculation
  images/make-dind/runner
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1000 Add go globals to autobumper
  config/autobump-config/testing-autobump-config.yaml
Labels: dco-signoff: yes, lgtm, approved

#1003 Change periodic cert-manager jobs to use cron
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/jobs/cert-manager/cert-manager/release-1.12/cert-manager-release-1.12.yaml
  config/jobs/cert-manager/cert-manager/release-1.13/cert-manager-release-1.13.yaml
  config/jobs/cert-manager/cert-manager/release-1.14/cert-manager-release-1.14.yaml
  config/prowgen/pkg/context.go
  config/prowgen/pkg/types.go
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1004 Further make-dind tuning of the docker service
  config/config.yaml
  images/make-dind/Dockerfile
  images/make-dind/runner
Labels: dco-signoff: yes, size/M, lgtm, approved

#1010 Add custom version of prow-controller-manager with better support for spot instances
  config/jobs/testing/testing-postsubmits-trusted.yaml
  images/prow-controller-manager-spot/Dockerfile
  images/prow-controller-manager-spot/README.md
  images/prow-controller-manager-spot/build.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1011 Improve docker networking options
  images/make-dind/Dockerfile
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1014 Restrict branchprotection branches, which are regexes
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1015 Run gencred less frequently since it causes prow components to restart
  config/gencred-config/gencred-config.yaml
  prow/cluster/gencred_deployment.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1008 With the new Makefile modules targets, we can more logically split the test Prowjobs
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/pkg/generators.go
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1019 Apply fixes for things we missed in #1008
  config/config.yaml
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/pkg/generators.go
Labels: size/XS, dco-signoff: yes, lgtm, approved
