Repository cert-manager/testing, pull requests merged in 2024-09, with the labels that each got.

#1050 Add test-e2e-ambient for 1.22 release
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, needs-ok-to-test, lgtm, approved

#1055 Add note explaining where a required check is defined
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1056 Add google-cas-issuer project
  config/config.yaml
  config/jobs/testing/testing-periodics-trusted.yaml
  triage_party/triageparty_configmap.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1058 Bump golang image for csi-lib
  config/jobs/cert-manager/csi-lib/cert-manager-csi-lib-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1057 Fix incorrect http01 acme solver configuration
  prow/cluster/gateway.yaml
  prow/cluster/letsencrypt-prod-issuer.yaml
  triage_party/letsencrypt-prod-issuer.yaml
  triage_party/triageparty_gateway.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1059 Update tested k8s versions to roughly match latest supported releases
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1060 Add k8s 1.31 test for cert-manager 1.15
  config/jobs/cert-manager/cert-manager/release-1.15/cert-manager-release-1.15.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1061 Setup tests for release-1.16
  config/config.yaml
  config/jobs/cert-manager/cert-manager/release-1.16/cert-manager-release-1.16.yaml
  config/plugins.yaml
  config/prowgen/prowspecs/specs.go
  config/testgrid/dashboards.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved
