Repository cert-manager/testing, pull requests merged in 2024-02, with the labels that each got.

#959 Move issuer-lib to prow (part of makefile modules refactor)
  config/config.yaml
  config/jobs/cert-manager/issuer-lib/cert-manager-issuer-lib-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#962 Update istio-csr prow e2e testing job
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved, ok-to-test

#963 Disallow force pushes and deletions for protected branches
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#965 Replace remaining jetstack names with cert-manager
  config/jobs/testing/testing-periodics-trusted.yaml
  config/jobs/testing/testing-postsubmits-trusted.yaml
  config/testgrid/dashboards.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#967 Enable 'Require a pull request before merging'
  config/config.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#969 Adds a job to run istio-csr ECC e2e suite
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved
