Repository cert-manager/testing, pull requests merged in 2024-07, with the labels that each got.

#1034 Bump go version for webhook-example presubmit job
  config/jobs/cert-manager/webhook-example/cert-manager-webhook-example-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1037 Rename required GH status for website PRs
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1039 Migrate to GKE Gateway API
  prow/cert-manager_install.sh
  prow/cluster/deck_service.yaml
  prow/cluster/gateway.yaml
  prow/cluster/hook_service.yaml
  prow/cluster/tls-ing_ingress.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#1036 Update tide config to allow auto-merging github-actions skip-review PRs
  config/config.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#1035 Add testing configuration for openshift-routes project
  config/jobs/cert-manager/openshift-routes/cert-manager-openshift-routes-presubmits.yaml
  config/jobs/testing/testing-periodics-trusted.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1041 Add openshift-routes smoke test
  config/jobs/cert-manager/openshift-routes/cert-manager-openshift-routes-presubmits.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#1042 Add missing repos to label-sync job
  config/jobs/testing/testing-periodics-trusted.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1043 Add the "gateway-shim" label
  config/labels.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1044 Remove unused K8S_VERSION environment variable from istio-csr tests
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1045 Add skip-review label to label-sync config
  config/labels.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1046 Update docs to reflect new processes, cluster names and project names
  README.md
  prow/README.md
  prow/version
Labels: dco-signoff: yes, size/M, lgtm, approved

#1047 Remove old istio versions from istio-csr tests
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1048 Add / update istio-csr e2e tests to use latest patch releases
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1049 Auto-run tests on PRs created by github-actions
  config/plugins.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#1052 Add istio-csr test for pure runtime configuration
  config/jobs/cert-manager/istio-csr/cert-manager-istio-csr-presubmits.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved
