Repository cert-manager/testing, pull requests merged in 2025-07, with the labels that each got.

#1098 Add config for cert-manager/webhook-cert-lib repo
  config/jobs/cert-manager/webhook-cert-lib/cert-manager-webhook-cert-lib-presubmits.yaml
  config/jobs/testing/testing-periodics-trusted.yaml
  triage_party/triageparty_configmap.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1099 Add GINKGO_NO_COLOR environment variable
  config/jobs/cert-manager/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1100 Add test-integration make target for cert-manager-webhook-cert-lib
  config/jobs/cert-manager/webhook-cert-lib/cert-manager-webhook-cert-lib-presubmits.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1102 Stale bot: staleness after 6 months, close after 1 year
  config/jobs/testing/testing-periodics-trusted.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved
