Repository cert-manager/testing, pull requests merged in 2025-09, with the labels that each got.

#1105 Add config for cert-manager/trust-manager-csi repo
  .gitignore
  config/config.yaml
  config/jobs/cert-manager/trust-manager-csi-driver/trust-manager-csi-driver-presubmits.yaml
  config/jobs/testing/testing-periodics-trusted.yaml
  triage_party/triageparty_configmap.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#1108 Preparing k8s v1.34 test suite
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1109 Making 1.34 default for master
  config/jobs/cert-manager/cert-manager/master/cert-manager-master.yaml
  config/prowgen/prowspecs/specs.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#1110 Remove archived cert-manager-olm configuration
  config/jobs/testing/testing-periodics-trusted.yaml
  triage_party/triageparty_configmap.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#1111 Update c-m required checks to K8s 1.34
  config/config.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved
